
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-09-29T10:32:36-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "dc4a007e4e902e51f97251390c8d1bbf7e58c6d3",
 "version": "0.1.4+15.gdc4a007"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
